config/routes.rb
Buzy::Application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  resources :users
  resources :places
  resources :votes
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'

  match '/vote', to: 'votes#new', via: 'get'
  match '/add', to: 'places#new', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/home', to: 'static_pages#home', via: 'get'

  get "places/new"
  get "votes/new"
  get "users/new"
  get '/places/:id', to: 'places#show'
  match 'places/:id/:time_ago', to: 'places#show', via: 'get'
  match 'places/:id/?q=:time_ago&submit=look', to: 'places#show', via: 'get'
  match 'places/:id/', to: 'places#show', via: 'post'
  match 'places/:id/vote', to: 'votes#new', via: 'post'

end

app/views/layouts/_footer.html.erb
 <div id="outside-container">
<footer class="footer">
  <small>
    BUZY by Kanav, Deven, Clement, Alex
  </small>
  <nav>
    <ul>
    	Created at <a href="http://make.bu.edu">Make_BU</a> 2014
    </ul>
  </nav>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "BUZY", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",  root_path %></li>
            <% if signed_in? %>
              <li><%= link_to "Users", '#' %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> BUZY </title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      
      <% flash.each do |key,value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>